//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INStore.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INStore.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        internal static string GeneralFlowDirection {
            get {
                return ResourceManager.GetString("GeneralFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginViewLogin {
            get {
                return ResourceManager.GetString("LoginViewLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginViewPassword {
            get {
                return ResourceManager.GetString("LoginViewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string LoginViewSignUp {
            get {
                return ResourceManager.GetString("LoginViewSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LoginViewUsername {
            get {
                return ResourceManager.GetString("LoginViewUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string NavigationBarAbout {
            get {
                return ResourceManager.GetString("NavigationBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string NavigationBarDashboard {
            get {
                return ResourceManager.GetString("NavigationBarDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string NavigationBarHome {
            get {
                return ResourceManager.GetString("NavigationBarHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Store.
        /// </summary>
        internal static string NavigationBarMyStore {
            get {
                return ResourceManager.GetString("NavigationBarMyStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string NavigationBarTools {
            get {
                return ResourceManager.GetString("NavigationBarTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string RegisterEmployeeViewBack {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string RegisterEmployeeViewEmployeeAddress {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewEmployeeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string RegisterEmployeeViewEmployeeDescription {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewEmployeeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        internal static string RegisterEmployeeViewEmployeeJob {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewEmployeeJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string RegisterEmployeeViewEmployeeName {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string RegisterEmployeeViewEmployeePhoneNumber {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewEmployeePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string RegisterEmployeeViewEmployeeSalary {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewEmployeeSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Ends At.
        /// </summary>
        internal static string RegisterEmployeeViewEmployeeShiftEndsAt {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewEmployeeShiftEndsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Starts At.
        /// </summary>
        internal static string RegisterEmployeeViewEmployeeShiftStartsAt {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewEmployeeShiftStartsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterEmployeeViewRegister {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string RegisterViewAdmin {
            get {
                return ResourceManager.GetString("RegisterViewAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Password.
        /// </summary>
        internal static string RegisterViewAdminPassword {
            get {
                return ResourceManager.GetString("RegisterViewAdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string RegisterViewEmployee {
            get {
                return ResourceManager.GetString("RegisterViewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string RegisterViewLogin {
            get {
                return ResourceManager.GetString("RegisterViewLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string RegisterViewNext {
            get {
                return ResourceManager.GetString("RegisterViewNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string RegisterViewPassword {
            get {
                return ResourceManager.GetString("RegisterViewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string RegisterViewUsername {
            get {
                return ResourceManager.GetString("RegisterViewUsername", resourceCulture);
            }
        }
    }
}
