//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INStore.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INStore.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Image.
        /// </summary>
        internal static string AddEditStoreItemViewAddImage {
            get {
                return ResourceManager.GetString("AddEditStoreItemViewAddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string AddEditStoreItemViewBareCode {
            get {
                return ResourceManager.GetString("AddEditStoreItemViewBareCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string AddEditStoreItemViewDescription {
            get {
                return ResourceManager.GetString("AddEditStoreItemViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN Stock.
        /// </summary>
        internal static string AddEditStoreItemViewINStock {
            get {
                return ResourceManager.GetString("AddEditStoreItemViewINStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN Store.
        /// </summary>
        internal static string AddEditStoreItemViewINStore {
            get {
                return ResourceManager.GetString("AddEditStoreItemViewINStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string AddEditStoreItemViewProductName {
            get {
                return ResourceManager.GetString("AddEditStoreItemViewProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        internal static string AddEditStoreItemViewPurchasePrice {
            get {
                return ResourceManager.GetString("AddEditStoreItemViewPurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string AddEditStoreItemViewSave {
            get {
                return ResourceManager.GetString("AddEditStoreItemViewSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Price.
        /// </summary>
        internal static string AddEditStoreItemViewSellingPrice {
            get {
                return ResourceManager.GetString("AddEditStoreItemViewSellingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoFill.
        /// </summary>
        internal static string AddItemViewModelAutoFill {
            get {
                return ResourceManager.GetString("AddItemViewModelAutoFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string AddItemViewModelSave {
            get {
                return ResourceManager.GetString("AddItemViewModelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Same Barcode Exist.
        /// </summary>
        internal static string AddStoreItemTheSameBarcodeExist {
            get {
                return ResourceManager.GetString("AddStoreItemTheSameBarcodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        internal static string GeneralFlowDirection {
            get {
                return ResourceManager.GetString("GeneralFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Not Found.
        /// </summary>
        internal static string LoginCommandNotFound {
            get {
                return ResourceManager.GetString("LoginCommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User : .
        /// </summary>
        internal static string LoginCommandTheUser {
            get {
                return ResourceManager.GetString("LoginCommandTheUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back .
        /// </summary>
        internal static string LoginCommandWelcomeBack {
            get {
                return ResourceManager.GetString("LoginCommandWelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password.
        /// </summary>
        internal static string LoginCommandWrongPassword {
            get {
                return ResourceManager.GetString("LoginCommandWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginViewLogin {
            get {
                return ResourceManager.GetString("LoginViewLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginViewPassword {
            get {
                return ResourceManager.GetString("LoginViewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string LoginViewSignUp {
            get {
                return ResourceManager.GetString("LoginViewSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LoginViewUsername {
            get {
                return ResourceManager.GetString("LoginViewUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add   .
        /// </summary>
        internal static string MyStoreAdd {
            get {
                return ResourceManager.GetString("MyStoreAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string MyStoreBareCode {
            get {
                return ResourceManager.GetString("MyStoreBareCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string MyStoreDelete {
            get {
                return ResourceManager.GetString("MyStoreDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string MyStoreEdit {
            get {
                return ResourceManager.GetString("MyStoreEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string MyStoreExport {
            get {
                return ResourceManager.GetString("MyStoreExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string MyStoreImport {
            get {
                return ResourceManager.GetString("MyStoreImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN Stock.
        /// </summary>
        internal static string MyStoreINStock {
            get {
                return ResourceManager.GetString("MyStoreINStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN Store.
        /// </summary>
        internal static string MyStoreINStore {
            get {
                return ResourceManager.GetString("MyStoreINStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        internal static string MyStorePurchasePrice {
            get {
                return ResourceManager.GetString("MyStorePurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search Products.
        /// </summary>
        internal static string MyStoresearchProducts {
            get {
                return ResourceManager.GetString("MyStoresearchProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Price.
        /// </summary>
        internal static string MyStoreSellingPrice {
            get {
                return ResourceManager.GetString("MyStoreSellingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string NavigationBarAbout {
            get {
                return ResourceManager.GetString("NavigationBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string NavigationBarDashboard {
            get {
                return ResourceManager.GetString("NavigationBarDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string NavigationBarHome {
            get {
                return ResourceManager.GetString("NavigationBarHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Store.
        /// </summary>
        internal static string NavigationBarMyStore {
            get {
                return ResourceManager.GetString("NavigationBarMyStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string NavigationBarTools {
            get {
                return ResourceManager.GetString("NavigationBarTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Already Exists.
        /// </summary>
        internal static string RegisterCommandUsernameAlreadyExists {
            get {
                return ResourceManager.GetString("RegisterCommandUsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Admin Password.
        /// </summary>
        internal static string RegisterCommandWrongAdminPassword {
            get {
                return ResourceManager.GetString("RegisterCommandWrongAdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string RegisterEmployeeViewBack {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string RegisterEmployeeViewEmployeeAddress {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewEmployeeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string RegisterEmployeeViewEmployeeDescription {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewEmployeeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        internal static string RegisterEmployeeViewEmployeeJob {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewEmployeeJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string RegisterEmployeeViewEmployeeName {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string RegisterEmployeeViewEmployeePhoneNumber {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewEmployeePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string RegisterEmployeeViewEmployeeSalary {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewEmployeeSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Ends At.
        /// </summary>
        internal static string RegisterEmployeeViewEmployeeShiftEndsAt {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewEmployeeShiftEndsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Starts At.
        /// </summary>
        internal static string RegisterEmployeeViewEmployeeShiftStartsAt {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewEmployeeShiftStartsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterEmployeeViewRegister {
            get {
                return ResourceManager.GetString("RegisterEmployeeViewRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string RegisterViewAdmin {
            get {
                return ResourceManager.GetString("RegisterViewAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Password.
        /// </summary>
        internal static string RegisterViewAdminPassword {
            get {
                return ResourceManager.GetString("RegisterViewAdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string RegisterViewEmployee {
            get {
                return ResourceManager.GetString("RegisterViewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string RegisterViewLogin {
            get {
                return ResourceManager.GetString("RegisterViewLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string RegisterViewNext {
            get {
                return ResourceManager.GetString("RegisterViewNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string RegisterViewPassword {
            get {
                return ResourceManager.GetString("RegisterViewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string RegisterViewUsername {
            get {
                return ResourceManager.GetString("RegisterViewUsername", resourceCulture);
            }
        }
    }
}
